version: "3.9"  # Optional: Specify a Docker Compose version

services:
  frontend:
    build: ./frontend  # Assuming 'frontend' contains your Dockerfile
    ports:
      - "8501:8501" 
    depends_on:
      - backend
    volumes:
      - ./frontend:/app 
    restart: always
    networks:
      - app
    container_name: frontend

  backend:
    build: ./backend   # Assuming 'backend' contains your Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app 
    restart: always
    networks:
      - app
    container_name: backend

networks:
  app:
    driver: bridge